### ISSUE TITLE
trouble with the git push command

### ISSUE THREAD

**Issue by johnnyxyz1223** [githubteacher/fluffy-octo-guacamole#53] opened 2016-05-11 17:34 UTC
git push --set-upstream jds-add-bio

results in:

fatal: the current branch jds-add-bio has no upstream branch.
To push the current branch and set the remote as upstream, use
git push --seet-upstream jds-add-bio jds-add-bio

**Comment by brianamarie** [comment] 2016-05-11 17:35
@johnnyxyz1223 Try this: `git push -u origin <branch-name>`

**Comment by johnnyxyz1223** [comment] 2016-05-11 17:39
That looks like it should work. But I need the command to set the outbound proxy.

I got:

fatal: unable to access 'https://github.com/githubteacher/fulffy-octo-guacamole.git/': The requested URL returned 403

I know the inbound proxy is ok because I was able to download to my pc

**Comment by brianamarie** [comment] 2016-05-11 17:40
Are you using the Allstate proxy, or do you have another proxy set up that you know of?  If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by TinmanAllstate** [comment] 2016-05-11 17:41
Same issue

**Comment by johnnyxyz1223** [comment] 2016-05-11 17:42
no I'm at Wells Fargo. I got it to work for the download by setting my .gitconfig

[http]
    proxy = http://{ourproxy}.wellsfargo.com:xxxx

**Comment by brianamarie** [comment] 2016-05-11 17:43
@TinmanAllstate Have you gotten in touch with Theodore Salvo regarding this issue? 

@johnnyxyz1223 Hooray! 🎉  I'm glad that you got it working. Please let me know here or in Gitter if you need any more help. https://gitter.im/githubteacher/fluffy-octo-guacamole

I'm going to close this issue, hopefully all is working well.  😄

**Comment by johnnyxyz1223** [comment] 2016-05-11 17:46
The git push command doesn't work. I can do the copy from GitHub but can't push up.

**Comment by brianamarie** [comment] 2016-05-11 17:47
@johnnyxyz1223 Okay. What is the message you get when you try?

**Comment by brianamarie** [comment] 2016-05-11 17:48
@johnnyxyz1223 Even though you aren't with Allstate, my best guess at the moment due to the same nature of the problem is that it's a network setting.  I think a bunch of folks having problems pushing are in the same position. Please feel free to just watch for now and then you can try the steps when you get the video later!

**Comment by johnnyxyz1223** [comment] 2016-05-11 17:52
I don't know. Here is the message I'm getting now:

command: git push -u origin jds-add-bio jds-add-bio

error:

error: dst ref refs/heads/jds-add-bio receives from more than one src.
error: failed to push some refs to 'https://github.com/githubteacher/fulffy-octo-guacamole.git'

maybe someone created a branch with the same name I did and got it pushed before me? If I had to guess.

**Comment by patrickmckenna** [comment] 2016-05-11 17:54
@johnnyxyz1223 Ah, so the command should be:

`git push -u origin jds-add-bio`

**Comment by johnnyxyz1223** [comment] 2016-05-11 17:56
I think that worked? Here is the output

C:\Users\seiberli\work\GitHub\fluffy-octo-guacamole [jds-add-bio]> git push -u origin jds-add-bio
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 607 bytes | 0 bytes/s, done.
Total 6 (delta 0), reused 0 (delta 0)
To https://github.com/githubteacher/fluffy-octo-guacamole.git
 * [new branch]      jds-add-bio -> jds-add-bio
Branch jds-add-bio set up to track remote branch jds-add-bio from origin.

**Comment by johnnyxyz1223** [comment] 2016-05-11 17:57
Now I just need to do the pull request. Missed all that trying to push.

**Comment by patrickmckenna** [comment] 2016-05-11 17:58
@johnnyxyz1223 yup, that worked!

**Comment by brianamarie** [comment] 2016-05-11 18:04
I'm going to close this issue (_again_), hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄

**Closed by brianamarie** 2016-05-11 18:04 UTC
